import { defineAsyncComponent } from 'vue';
export const AppModal = defineAsyncComponent(() => import('./app-modal.vue'));
export const AppAction = defineAsyncComponent(() => import('./app-action.vue'));
export const AppAnchor = defineAsyncComponent(() => import('./app-anchor.vue'));
export const AppCode = defineAsyncComponent(() => import('./app-code.vue'));
export const AppDrawer = defineAsyncComponent(() => import('./app-drawer.vue'));
export const AppIcon = defineAsyncComponent(() => import('./app-icon.vue'));
export const AppTabs = defineAsyncComponent(() => import('./app-tabs.vue'));
export const AppLink = defineAsyncComponent(() => import('./app-link.vue'));
export const AppLogin = defineAsyncComponent(() => import('./app-login.vue'));
export const AppEchart = defineAsyncComponent(() => import('./app-echart.vue'));
